CREATE DATABASE HEALTHCARE_DATA_DB;
CREATE SCHEMA HEALTHCARE_DATA_DB.GOLD_LAYER;
CREATE WAREHOUSE HEALTHCARE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DATA_DB;
USE SCHEMA GOLD_LAYER;
SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();

SHOW TABLES;
SELECT * FROM DIM_PATIENT LIMIT 10;
SELECT * FROM DIM_HOSPITAL LIMIT 10;
SELECT * FROM DIM_CONDITION LIMIT 10;
SELECT * FROM FACT_HEALTHCARE LIMIT 10;

SELECT COUNT(*) FROM DIM_PATIENT;
SELECT COUNT(*) FROM FACT_HEALTHCARE;

ey;
SELECT
    d.Age,
    d.Gender,
f."BILLING AMOUNT"
FROM FACT_HEALTHCARE f
JOIN DIM_PATIENT d
ON f.patient_key = d.patient_k
